resolver: lts-6.9
packages:
- '.'

extra-deps:
- monomorphic-0.0.3.3
- singletons-2.1
- ghc-typelits-natnormalise-0.4.6
- th-desugar-1.6
- type-natural-0.4.1.0
- equational-reasoning-0.4.0.0
- ghc-typelits-presburger-0.1.0.0

flags: {}

extra-package-dbs: []
